name: test2

on:
  workflow_dispatch:

jobs:
  node24-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4
      - name: Check migrations changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            migrations:
              - 'backend/*/migrations/**'

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SECRET_SSH_KEY }}

      - uses: actions/setup-node@v4
      - name: Generate next version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          branch: main
          major_pattern: "major!"
          minor_pattern: "minor!"
          bump_each_commit: false
          version_format: "${major}.${minor}.${patch}"